- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure VDOM settings.
    fortios_system_settings:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      system_settings:
        comments: ''
        opmode: nat
        inspection-mode: proxy
        ngfw-mode: profile-based
        implicit-allow-dns: enable
        ssl-ssh-profile: certificate-inspection
        http-external-dest: fortiweb
        firewall-session-dirty: check-all
        manageip: ''
        gateway: 0.0.0.0
        ip: 0.0.0.0 0.0.0.0
        manageip6: "::/0"
        gateway6: "::"
        ip6: "::/0"
        device: ''
        bfd: disable
        bfd-desired-min-tx: 250
        bfd-required-min-rx: 250
        bfd-detect-mult: 3
        bfd-dont-enforce-src-port: disable
        utf8-spam-tagging: enable
        wccp-cache-engine: disable
        vpn-stats-log: ipsec
        vpn-stats-period: 600
        v4-ecmp-mode: source-ip-based
        mac-ttl: 300
        fw-session-hairpin: disable
        prp-trailer-action: disable
        snat-hairpin-traffic: enable
        dhcp-proxy: disable
        dhcp-server-ip: ''
        dhcp6-server-ip: ''
        central-nat: disable
        gui-default-policy-columns: []
        lldp-transmission: global
        link-down-access: enable
        asymroute: disable
        asymroute-icmp: disable
        tcp-session-without-syn: disable
        ses-denied-traffic: disable
        strict-src-check: disable
        asymroute6: disable
        asymroute6-icmp: disable
        sip-helper: disable
        sip-nat-trace: enable
        status: enable
        sip-tcp-port: 5060
        sip-udp-port: 5060
        sip-ssl-port: 5061
        sccp-port: 2000
        multicast-forward: enable
        multicast-ttl-notchange: disable
        multicast-skip-policy: disable
        allow-subnet-overlap: disable
        deny-tcp-with-icmp: disable
        ecmp-max-paths: 10
        discovered-device-timeout: 28
        email-portal-check-dns: enable
        default-voip-alg-mode: proxy-based
        gui-icap: disable
        gui-nat46-64: disable
        gui-implicit-policy: enable
        gui-dns-database: disable
        gui-load-balance: disable
        gui-multicast-policy: disable
        gui-dos-policy: enable
        gui-object-colors: enable
        gui-replacement-message-groups: disable
        gui-voip-profile: disable
        gui-ap-profile: enable
        gui-dynamic-profile-display: disable
        gui-local-in-policy: disable
        gui-local-reports: disable
        gui-wanopt-cache: disable
        gui-explicit-proxy: disable
        gui-dynamic-routing: enable
        gui-dlp: disable
        gui-sslvpn-personal-bookmarks: disable
        gui-sslvpn-realms: disable
        gui-policy-based-ipsec: disable
        gui-threat-weight: enable
        gui-multiple-utm-profiles: enable
        gui-spamfilter: disable
        gui-application-control: enable
        gui-ips: enable
        gui-endpoint-control: enable
        gui-endpoint-control-advanced: disable
        gui-dhcp-advanced: enable
        gui-vpn: enable
        gui-wireless-controller: enable
        gui-switch-controller: enable
        gui-fortiap-split-tunneling: disable
        gui-webfilter-advanced: disable
        gui-traffic-shaping: enable
        gui-wan-load-balancing: enable
        gui-antivirus: enable
        gui-webfilter: enable
        gui-dnsfilter: enable
        gui-waf-profile: disable
        gui-fortiextender-controller: disable
        gui-advanced-policy: disable
        gui-allow-unnamed-policy: disable
        gui-email-collection: disable
        gui-domain-ip-reputation: disable
        gui-multiple-interface-policy: disable
        gui-policy-learning: enable
        compliance-check: disable
        ike-session-resume: disable
        ike-quick-crash-detect: disable
        ike-dn-format: with-space
        block-land-attack: disable
