- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure profile groups.
    fortios_firewall_profile_group:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_profile_group:
        state: "present"
        application-list: "default"
        av-profile: "default"
        dnsfilter-profile: "default"
        ips-sensor: "default"
        name: "profile_group1"
        profile-protocol-options: "default"
        ssl-ssh-profile: "deep-inspection"
        voip-profile: "default"
        waf-profile: "default"
        webfilter-profile: "default"
